// PAGE REDUCER 
export const SET_PAGE = 'SET_PAGE';
export const SET_USER = 'SET_USER'; 

// APPLICATION REDUCER 
export const ADD_APPLICATION = 'ADD_APPLICATION'
export const DELETE_APPLICATION = 'DELETE_APPLICATION'
export const UPDATE_APPLICATION = 'UPDATE_APPLICATION'